import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import Header from '@/components/layouts/Header/Header';
import Footer from '@/components/layouts/Footer';

const fontFamily = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] });

export const metadata: Metadata = {
    title: 'Bất động sản chỉnh chủ',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true} className={fontFamily.className}>
                <div className="relative">
                    <Header />
                    <div className="relative pt-[64px]"> {children}</div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
